structure(list(url = "https://public-api.meteofrance.fr/public/DPClim/v1/commande-station/quotidienne?id-station=75114001&date-deb-periode=2020-01-01T00%3A00%3A00Z&date-fin-periode=2020-12-31T23%3A59%3A59Z", 
    status_code = 202L, headers = structure(list(activityid = "2931b687-d524-46a4-8f54-7a519946791d", 
        `access-control-expose-headers` = "", `access-control-allow-origin` = "*", 
        `access-control-allow-methods` = "GET", `access-control-allow-headers` = "authorization,Access-Control-Allow-Origin,Content-Type,SOAPAction,apikey,Internal-Key,Authorization", 
        `content-type` = "application/json", date = "Thu, 26 Mar 2026 18:54:41 GMT", 
        `transfer-encoding` = "chunked"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 202L, version = "HTTP/1.1", 
        headers = structure(list(activityid = "2931b687-d524-46a4-8f54-7a519946791d", 
            `access-control-expose-headers` = "", `access-control-allow-origin` = "*", 
            `access-control-allow-methods` = "GET", `access-control-allow-headers` = "authorization,Access-Control-Allow-Origin,Content-Type,SOAPAction,apikey,Internal-Key,Authorization", 
            `content-type` = "application/json", date = "Thu, 26 Mar 2026 18:54:41 GMT", 
            `transfer-encoding` = "chunked"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = c("public-api.meteofrance.fr", 
    "public-api.meteofrance.fr"), flag = c(FALSE, FALSE), path = c("/", 
    "/"), secure = c(FALSE, FALSE), expiration = structure(c(Inf, 
    Inf), class = c("POSIXct", "POSIXt")), name = c("LSW_WEB", 
    "TS01920678"), value = c("REDACTED", "REDACTED")), row.names = c(NA, 
    -2L), class = "data.frame"), content = charToRaw("{\"elaboreProduitAvecDemandeResponse\": {\"return\": \"2026010476359\"}}"), 
    date = structure(1774551281, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.696684, 
    connect = 0.773487, pretransfer = 0.857148, starttransfer = 0.98266, 
    total = 0.982717)), class = "response")
