#' Download SYNOP data from Meteo-France open data
#'
#' Downloads SYNOP surface observation data from the Meteo-France open data
#' portal for a given year, decompresses the archive, and return a data frame.
#'
#' SYNOP data come from observation messages exchanged
#' through the World Meteorological Organization (WMO) Global Telecommunication
#' System (GTS). These observations include measured atmospheric parameters
#' such as temperature, humidity, wind direction and speed, atmospheric pressure,
#' and precipitation amount, as well as observed variables such as present weather,
#' cloud description, and visibility. Depending on instrumentation and local
#' conditions, additional variables may be available (e.g., snow depth, ground
#' state).
#'
#' The dataset covers mainland France and overseas territories with a typical
#' observation frequency of 3 hours. Available years cover 1996 to present.
#'
#' @param year Numeric or character. Year of the data to download (YYYY), between 1996 and present year (included).
#' @param path Path to folder where to save the archive. Default to \code{tempdir()}.
#'
#' @return A data.frame containing the downloaded data.
#'
#' @details
#' Data description and documentation is available here (French):
#' \url{https://meteo.data.gouv.fr/datasets/686f8595b351c06a3a790867}
#'
#' Files are downloaded as \code{.csv.gz}, decompressed on the fly, and read.
#' Typical size of compressed files is <7MB for period 1996-2024 and <20MB for more recent years.
#' Missing values coded as "", "NA", or "mq" are converted to NA in the returned data frame.
#'
#'
#' @export
#'
#' @examples
#' \dontrun{
#' mfclim_synop(2020, TRUE)
#' mydata <- mfclim_synop(2020, FALSE)
#' }
mfclim_synop <- function(year, path=tempdir()){

  if (as.numeric(year) < 1996 | as.numeric(year) > format(Sys.Date(),"%Y")){
    stop(paste0("Year ",year," is not in the interval 1996-",format(Sys.Date(),"%Y")))
  }

  # Specify the URL of the file you want to download
  # Specify the file name and location where you want to save the file on your computer
  url <- paste0("https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/OBS/SYNOP/synop_",year,".csv.gz")
  object_name <- paste0("synop.",year)
  archive_name <- paste0(path,"/",object_name,".csv.gz")

  # Call the download.file() function, passing in the URL and file name/location as arguments
  download.file(url, archive_name, mode = "wb")

  #
  if (file.exists(archive_name)){
    message(paste0("The archive has been saved to ",archive_name))
  } else {
    stop("Download failed")
  }

  # uncompresses downloaded file and create a data.frame
  table <- read.csv(gzfile(archive_name),sep = ";", na.strings = c("", "NA", "mq"))

  return(table)
}

#' Get Meteo-France API access token
#'
#' Request an OAuth2 access token from the Meteo-France API using the
#' client credentials authentication flow.
#'
#' Requires a valid account on the Meteo-France API portal \url{https://portail-api.meteofrance.fr} and
#' a (free) subscription to the 'Climatological data' API (\url{https://portail-api.meteofrance.fr/web/en/api/DonneesPubliquesClimatologie}).
#' The `client_auth` value must be obtained from your account on the Meteo-France API portal:
#'    - Go to 'My API' -> 'Climatological data' -> 'Generate Token' -> 'Curl'
#'    - Copy the string that appears after "Authorization: Basic" in the provided curl command (remove the trailing `"`).
#'
#' @param client_auth Character string. Authentication identifier provided by the
#'   Meteo-France API portal (string following "Authorization: Basic").
#'
#' @return A character string containing the access token used to authenticate
#'   subsequent API requests.
#'
#'
#' @export
#'
#' @examples
#' \dontrun{
#' token <- mfclim_get_token(client_auth)
#' }
mfclim_get_token <- function(client_auth) {

  url <- "https://portail-api.meteofrance.fr/token"

  res <- POST(
    url,
    add_headers(
      Authorization = paste("Basic", client_auth)
    ),
    body = list(grant_type = "client_credentials")
  )

  token <- content(res)$access_token

  if (!is.null(token)){
    return(token)
  } else {
    stop(
      paste0(
        "Failed to obtain access token. Please check your credentials ",
        "(client_auth argument).\nServer response:\n",
        content(res)
      )
    )
  }
}

#' Order climate data for a station from the Meteo-France API
#'
#' Submit an asynchronous order for climatological data from a
#' Meteo-France station. The function returns a order ID that must be used
#' later to download the data file.
#'
#' The order is asynchronous: the data file is generated by the server and
#' must be retrieved afterward using the order ID.
#'
#' @param token Character string. OAuth2 access token obtained with
#'   \code{mfclim_get_token()}.
#' @param station Character string. Station identifier (8-digit station code).
#' @param step Character string. Time step of the ordered data. One of:
#'   \code{"6m"} (6 minutes), \code{"1h"} (hourly), \code{"1d"} (daily),
#'   \code{"10d"} (10-day), \code{"1mo"} (monthly).
#' @param date_deb Character string. Start date of the requested period in
#'   ISO 8601 UTC format (e.g. "2020-01-01T00:00:00Z"). If \code{step = "6m"}, minutes value must be a multiple of 6 (00, 06, 12, 18, 24, 30, 36, 42, 48, 54).
#' @param date_fin Character string. End date of the requested period in
#'   ISO 8601 UTC format (e.g. "2020-12-31T23:59:59Z"). If \code{step = "6m"}, minutes value must be a multiple of 6 (00, 06, 12, 18, 24, 30, 36, 42, 48, 54).
#'
#' @return Numeric or character value corresponding to the order ID.
#'   This ID must be used to download the data file.
#'
#' @seealso \code{mfclim_download()}
#'
#' @export
#'
#' @examples
#' \dontrun{
#' id_cmd <- mfclim_order(
#'   token,
#'   station = "75114001",
#'   step = "1d",
#'   date_deb = "2020-01-01T00:00:00Z",
#'   date_fin = "2020-12-31T23:59:59Z"
#' )
#' }
mfclim_order <- function(token, station, step = c("1mo", "10d","1d","1h","6m"), date_deb, date_fin) {

  step <- match.arg(step)

  data <- switch(step,
                 "6m" = "infrahoraire-6m",
                 "1h" = "horaire",
                 "1d" = "quotidienne",
                 "10d" = "decadaire",
                 "1mo" = "mensuelle"
  )

  url <- paste0("https://public-api.meteofrance.fr/public/DPClim/v1/commande-station/",data)

  res <- GET(
    url,
    add_headers(
      Authorization = paste("Bearer", token)
    ),
    query = list(
      `id-station` = station,
      `date-deb-periode` = date_deb,
      `date-fin-periode` = date_fin
    )
  )

  status <- mfclim_check_status(res)


  if (status == 202) {
    message("Data order accepted")
    cmd <- content(res)
    return(cmd$elaboreProduitAvecDemandeResponse$return)
  }
}

#' Download a climate data file from the Meteo-France API
#'
#' Download the CSV file corresponding to a previously submitted data order
#' . The function repeatedly queries the API until the file is ready
#' and then downloads it to disk.
#'
#' @param token Character string. OAuth2 access token obtained with
#'   \code{mfclim_get_token()}.
#' @param id_cmde Numeric or character. Order ID returned by
#'   \code{mfclim_order()}.
#' @param filename Character string. Name of the output CSV file.
#' @param folder Character string. Where to save the downloaded CSV file. Default to \code{tempdir()}
#'
#' @return Character string. Path to the downloaded file.
#'
#' @details The function polls the API every 5 seconds until the file is
#'   available. When the file is ready, it is downloaded and saved to
#'   \code{filename}.
#'
#' @seealso \code{mfclim_order()}
#'
#' @export
#'
#' @examples
#' \dontrun{
#' file <- mfclim_download(token, id_cmde = 123456, filename = "meteo.csv")
#' }
mfclim_download <- function(token, id_cmde, filename = "data.csv", folder = tempdir()) {

  url <- "https://public-api.meteofrance.fr/public/DPClim/v1/commande/fichier"
  filepath <- paste0(folder,"/",filename)
  filepath <- gsub(pattern="//", replacement="/", x=filepath)

  repeat {

    res <- GET(
      url,
      add_headers(
        Authorization = paste("Bearer", token)
      ),
      query = list(`id-cmde` = id_cmde),
      write_disk(filepath, overwrite = TRUE)
    )

    if (status_code(res) == 201) {
      message("File downloaded successfully.")
      message(paste0("The file has been saved to ",filepath))
      break
    }

    if (status_code(res) == 204) {
      message("File not ready yet. Retrying in 5 seconds...")
      Sys.sleep(5)
    }

    if (status_code(res) >= 400) {
      mfclim_check_status(res)
    }
  }

  return(filepath)
}

#' Download archived meteorological data from the Meteo-France "Donnees Climatologiques" API in one step
#'
#' This is a wrapper function that retrieves data from the
#' Climatological Data API for a given station and period. The function can
#' either use an existing token or automatically request a new token
#' using client credentials.
#'
#' The function:
#' \enumerate{
#'   \item Obtains an access token if not provided
#'   \item Submits a data order
#'   \item Waits for the file to be generated
#'   \item Downloads the CSV file
#'   \item Reads the CSV file into R
#' }
#'
#' @param client_auth Character string. Authentication string provided by the
#'   Meteo-France API portal (optional if \code{token} is provided).
#' @param token Character string. OAuth2 access token obtained with
#'   \code{mfclim_get_token()} (optional if \code{client_auth} is provided).
#' @param station Character string. Station identifier.
#' @param step Character string. Time step of the requested data.
#' @param date_deb Character string. Start date in ISO 8601 *UTC* format (see example). If \code{step = "6m"}, minutes values must be multiples of 6 (00, 06, 12, 18, 24, 30, 36, 42, 48, 54).
#' @param date_fin Character string. End date in ISO 8601 *UTC* format. If \code{step = "6m"}, minutes values must be multiples of 6 (00, 06, 12, 18, 24, 30, 36, 42, 48, 54).
#' @param filename Character string. Name of the downloaded CSV file. Default to
#' @param folder Character string. Where to save the downloaded CSV file. Default to \code{tempdir()}.
#'
#' @return A data.frame containing the climate data.
#'
#' @seealso
#' \code{mfclim_get_token()},
#' \code{mfclim_order()},
#' \code{mfclim_download()}
#'
#'
#' @export
#'
#' @examples
#' \dontrun{
#' data <- mfclim_get_data(
#'   client_auth = client_auth,
#'   station = "75114001",
#'   step = "1d",
#'   date_deb = "2020-01-01T00:00:00Z",
#'   date_fin = "2020-12-31T23:59:59Z"
#' )
#' }
mfclim_get_data <- function(
    token,
    client_auth,
    station,
    step,
    date_deb,
    date_fin,
    filename = "data.csv",
    folder = tempdir()
) {

  if (missing(token) & !missing(client_auth)){
    message("Token is missing. Attempting to obtain one using client credentials (client_auth argument).")
    token <- mfclim_get_token(client_auth)
  } else if (missing(token) & missing(client_auth)){
    stop("Either 'client_auth' or 'token' must be provided.")
  }

  id_cmde <- mfclim_order(
    token,
    station,
    step,
    date_deb,
    date_fin
  )

  Sys.sleep(2)

  file <- mfclim_download(token, id_cmde, filename = filename, folder = folder)

  data <- read.csv2(file)

  return(data)
}


#' Get the list of Meteo-France stations by department
#'
#' Retrieve the list of available Meteo-France stations for a given French
#' department and data frequency. The list can optionally be filtered by
#' meteorological parameter.
#'
#' @param token Character string. OAuth2 access token obtained with
#'   \code{mfclim_get_token()}.
#' @param client_auth Character string. Authentication string provided by the
#'   Meteo-France API portal. Used to automatically obtain a token if
#'   \code{token} is not provided.
#' @param departement Character or numeric. French department code.
#' @param step Character string. Data frequency. One of:
#'   \code{"1d"} (daily), \code{"1h"} (hourly), \code{"6m"} (6 minutes).
#' @param parametre Character string. Optional meteorological parameter used
#'   to filter stations. One of:
#'   \code{"precipitation"}, \code{"temperature"}, \code{"humidite"},
#'   \code{"vent"}, \code{"pression"}, \code{"rayonnement"},
#'   \code{"insolation"}, \code{"etat_mer"}, \code{"evapo"}.
#'
#' @return A data.frame containing the list of stations and their metadata.
#'
#' @details If \code{token} is not provided, the function will automatically
#'   request a new token using \code{client_auth}.
#'
#'
#' @export
#'
#' @examples
#' \dontrun{
#' stations <- mfclim_list_stations(
#'   client_auth = client_auth,
#'   departement = "75",
#'   step = "1d",
#'   parametre = "temperature"
#' )
#' }
mfclim_list_stations <- function(token,
                              client_auth,
                              departement,
                              step = c("1d","1h","6m"),
                              parametre = NULL) {

  if (missing(token) & !missing(client_auth)){
    message("Token is missing. Attempting to obtain one using client credentials (client_auth argument).")
    token <- mfclim_get_token(client_auth)
  } else if (missing(token) & missing(client_auth)){
    stop("Either 'client_auth' or 'token' must be provided.")
  }

  step <- match.arg(step)

  if (step == "6m"){
    freq <- "infrahoraire-6m"
  } else if (step == "1h"){
    freq <- "horaire"
  } else if (step == "1d"){
    freq <- "quotidienne"
  }

  base_url <- "https://public-api.meteofrance.fr/public/DPClim/v1/liste-stations/"
  url <- paste0(base_url, freq)

  query_list <- list(`id-departement` = departement)

  if (!is.null(parametre)) {
    parametre <- match.arg(parametre,
                           c("precipitation", "temperature", "humidite",
                             "vent", "pression", "rayonnement",
                             "insolation", "etat_mer", "evapo"))
    query_list$parametre <- parametre
  }

  res <- GET(
    url,
    add_headers(
      Authorization = paste("Bearer", token)
    ),
    query = query_list
  )

  status <- mfclim_check_status(res)

  if (status == 200) {
    stations <- content(res, as = "parsed")
    stations <- do.call(rbind, lapply(stations, as.data.frame))
    return(stations)
  }
}

#' Get information about a Meteo-France station
#'
#' Retrieve metadata and information for a given Meteo-France station
#' using its station identifier.
#'
#' @param token Character string. OAuth2 access token obtained with
#'   \code{mfclim_get_token()}.
#' @param client_auth Character string. Authentication string provided by the
#'   Meteo-France API portal. Used to automatically obtain a token if
#'   \code{token} is not provided.
#' @param station Character string. Station identifier (8-digit station code).
#'
#' @return A list containing station metadata. Scalar elements are returned
#'   as vectors, and nested list elements are converted into data frames.
#'
#' @details If \code{token} is not provided, the function will automatically
#'   request a new token using \code{client_auth}. The returned list structure
#'   depends on the API response and may include station metadata, location,
#'   altitude, opening and closing dates, and available parameters.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' info <- mfclim_info_station(
#'   client_auth = client_auth,
#'   station = "75114001"
#' )
#' }
mfclim_info_station <- function(token,
                                   client_auth,
                                   station) {

  if (missing(token) & !missing(client_auth)){
    message("Token is missing. Attempting to obtain one using client credentials (client_auth argument).")
    token <- mfclim_get_token(client_auth)
  } else if (missing(token) & missing(client_auth)){
    stop("Either 'client_auth' or 'token' must be provided.")
  }

  url <- "https://public-api.meteofrance.fr/public/DPClim/v1/information-station"

  res <- GET(
    url,
    add_headers(
      Authorization = paste("Bearer", token)
    ),
    query = list(`id-station` = station)
  )

  status <- mfclim_check_status(res)

  if (status == 200) {
    info <- content(res, as = "parsed")[[1]]
    info_parsed <- mfclim_parse_json(info)
    return(info_parsed)
  }

}

#' Check HTTP response status from Meteo-France API
#'
#' Verifies the HTTP status code of a response object returned by a
#' Meteo-France API request. If the status code indicates an error,
#' a descriptive message is returned and the function stops execution.
#'
#' @param res Response object returned by \code{httr2::GET()} or \code{httr2::POST()}.
#'
#' @return Integer. HTTP status code of the response.
#'
#' @details If the API returns an error (status >= 400), the function stops
#'   and prints a descriptive message including the status code and the
#'   content of the API response.
#'
#'
mfclim_check_status <- function(res) {

  status <- status_code(res)

  messages <- c(
    "400" = "Incorrect parameters",
    "401" = "Not authorized (invalid token)",
    "403" = "Denied access",
    "404" = "Unknown station, department, or order number",
    "429" = "Max number of requests has been reached",
    "500" = "Server internal error",
    "502" = "API gateway error",
    "503" = "Service unavailable",
    "504" = "Server timeout"
  )

  if (status >= 400) {
    msg <- messages[as.character(status)]
    msgAPI <- content(res)
    if (is.na(msg)) msg <- "Unknow API error code"
    stop(paste0("Error ", status, ": ", msg,",\n
                message returned by the server: ", msgAPI))
  }

  return(status)
}


#' Parse a JSON-like list from Meteo-France API into R structures
#'
#' Converts a parsed JSON object (list) returned by the Meteo-France API
#' into a more convenient R structure. Simple values are stored as vectors,
#' while nested lists are converted into data.frames.
#'
#' @param x A named list, typically obtained from \code{httr2::content(..., as="parsed")}.
#'
#' @return A named list where:
#'   - simple values are stored as vectors,
#'   - nested lists are converted into data.frames via \code{do.call(rbind, ...)}.
#'
#' @details Used for transforming the structure returned by
#'   \code{mfclim_info_station} into a more user-friendly format.
#'
#'
mfclim_parse_json <- function(x) {

  out <- list()

  for (n in names(x)) {

    element <- x[[n]]

    # Si valeur simple
    if (!is.list(element)) {
      out[[n]] <- element
    }

    # Si liste -> data.frame
    else {
      out[[n]] <- do.call(
        rbind,
        lapply(element, function(e) {
          as.data.frame(e, stringsAsFactors = FALSE)
        })
      )
    }
  }

  return(out)
}
